name: Build library
run-name: Build library by ${{ github.actor }}

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: read
  packages: write

env:
  qt_version: ${{ vars.QT_VERSION }}
  qt_checkout_tag: ${{ vars.QT_CHECKOUT_TAG }}
  build_options: '-webengine-proprietary-codecs -webengine-full-debug-info'
  build_type_option: ""

jobs:
  build_linux:
    name: Build for Linux
    runs-on: [ ubuntu-22.04 ]
    timeout-minutes: 1440

    env:
      build_dir: './build'
      install_prefix: '${{ github.workspace }}/install_linux'
      build_opts: |
        -webengine-proprietary-codecs \
        -webengine-full-debug-info \

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bison build-essential flex git gperf gyp python3-pip \
            libasound2-dev libatspi2.0-dev libavcodec-dev libavformat-dev libavutil-dev libcups2-dev libgbm-dev \
            libdbus-1-dev libdrm-dev libegl1-mesa-dev libevent-dev libfontconfig1-dev libfreetype6-dev libicu-dev libjsoncpp-dev libminizip-dev \
            libnss3-dev libopus-dev libpci-dev libprotobuf-dev libpulse-dev libre2-dev libsnappy-dev libsrtp2-dev libssl-dev libudev-dev libvpx-dev \
            libwebp-dev libx11-dev libx11-xcb-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev \
            libxcb-render-util0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync0-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xinerama0-dev \
            libxcb-xkb-dev libxcb1-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev libxfixes-dev libxi-dev libxkbcommon-dev \
            libxkbcommon-x11-dev libxkbfile-dev libxrandr-dev libxrender-dev libxshmfence-dev libxss-dev libxtst-dev \
            ninja-build ninja-build nodejs protobuf-compiler

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          dir: /opt/qt
          tools: 'tools_ninja'
          modules: 'qtshadertools'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.24.3'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.10.0 <3.10.10'

      - name: Install python modules
        run: |
          python3 --version
          pip install html5lib

      - name: Get QtWebEngine sources
        run: |
          if [ ! -d qt/qtwebengine/.git ]
          then
            mkdir qt && cd qt
            git clone https://github.com/qt/qtwebengine.git

            cd qtwebengine

            git checkout ${{ env.qt_checkout_tag }}

            git submodule init
            git submodule update
          else
            cd qt/qtwebengine
            git pull origin ${{ env.qt_checkout_tag }}
          fi

          cd ..

      - name: Configure QtWebEngine
        run: |
          cd qt

          rm -rf ${{ env.build_dir }}
          mkdir ${{ env.build_dir }} && cd ${{ env.build_dir }}
          mkdir qtwebengine && cd qtwebengine

          ${{ env.QT_ROOT_DIR }}/bin/qt-configure-module ../../qtwebengine ${{ env.build_opts }} -- ${{ env.build_type_option }} -DCMAKE_INSTALL_PREFIX=${{ env.install_prefix }}

      - name: Build QtWebEngine
        run: |
          cd qt/build/qtwebengine

          cmake --build . --parallel
          cmake --install .

      - name: 'Tar files (to preserve symlinks)'
        run: tar -cvf qtwebengine.tar -C ${{ env.install_prefix }} .

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: qtwebengine-linux
          path: qtwebengine.tar

  build_windows:
    name: Build for Windows
    runs-on: [ windows-self-hosted ]
    timeout-minutes: 1440
    if: false

    env:
      checkout_dir: 'D:\qtwe\src'
      build_dir: 'D:\qtwe\build'
      install_prefix: 'D:\qtwe\install'
      qt_dir: 'D:\opt'
      qt_tools_dir: ${{ github.workspace }}/Qt/Tools
      cmake_c_compiler: 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\cl.exe'
      cmake_cxx_compiler: 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\cl.exe'
      vcvars: 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat'

    steps:
      - name: Prepare environment
        shell: pwsh
        run: |
          $p = "HKLM:\System\CurrentControlSet\Control\Filesystem"
          Get-ItemPropertyValue $p LongPathsEnabled
          Set-ItemProperty $p LongPathsEnabled 1
          Get-ItemPropertyValue $p LongPathsEnabled

          mkdir -F ${{ env.checkout_dir }}
          mkdir -F ${{ env.build_dir }}

      - name: Prepare tools
        run: |
          perl -v
          choco install -f -y gperf winflexbison3

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          arch: 'win64_msvc2022_64'
          dir: ${{ env.qt_dir }}
          tools: 'tools_ninja'
          modules: 'qtshadertools'

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.24.3'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.10.0 <3.10.10'

      - name: Install python modules
        run: |
          python3 --version
          pip install html5lib

      - name: Get QtWebEngine sources
        working-directory: ${{ env.checkout_dir }}
        run: |
          git clone git://code.qt.io/qt/qtwebengine.git .

          git checkout ${{ env.qt_checkout_tag }}
          git submodule init
          git submodule update

      - name: Configure QtWebEngine
        shell: cmd
        working-directory: ${{ env.build_dir }}
        run: |
          call "${{ env.vcvars }}"

          ${{ env.QT_ROOT_DIR }}\bin\qt-configure-module.bat ${{ env.checkout_dir }} ${{ env.build_options }} -- ${{ env.build_type_option }} -DCMAKE_INSTALL_PREFIX=${{ env.install_prefix }}

      - name: Build QtWebEngine
        shell: cmd
        working-directory: ${{ env.build_dir }}
        run: |
          call "${{ env.vcvars }}"

          cmake --build . --parallel
          cmake --install .

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: qtwebengine-windows
          path: ${{ env.install_prefix }}

  build_macos:
    name: Build for MacOS
    runs-on: [ macos-self-hosted ]
    timeout-minutes: 1440
    if: false

    env:
      build_dir: './build'
      install_prefix: '${{ github.workspace }}/install_macos'
      libs_dir: '${{ github.workspace }}/libs_deps'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Prepare libraries
        run: |
          brew install gperf bison flex

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          dir: ${{ github.workspace }}/opt
          tools: 'tools_ninja'
          modules: 'qtshadertools'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.24.3'

      # - name: Install Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '>=3.10.0 <3.10.10'

      - name: Install python modules
        run: |
          python3 --version
          pip install html5lib

      - name: Get QtWebEngine sources
        run: |
          mkdir qt && cd qt

          git clone git://code.qt.io/qt/qtwebengine.git
          cd qtwebengine
          git checkout ${{ env.qt_checkout_tag }}
          git submodule init
          git submodule update
          cd ..

      - name: Configure QtWebEngine
        run: |
          cd qt

          mkdir ${{ env.build_dir }} && cd ${{ env.build_dir }}
          mkdir qtwebengine
          cd qtwebengine

          ls -la ${{ github.workspace }}/qt/qtwebengine

          ${{ env.QT_ROOT_DIR }}/bin/qt-configure-module ${{ github.workspace }}/qt/qtwebengine ${{ env.build_options }} -- ${{ env.build_type_option }} -DCMAKE_INSTALL_PREFIX=${{ env.install_prefix }}

      - name: Build QtWebEngine
        run: |
          cd qt/build/qtwebengine

          cmake --build . --parallel
          cmake --install .

      - name: 'Tar files (to preserve symlinks)'
        run: tar -cvf qtwebengine.tar -C ${{ env.install_prefix }} .

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: qtwebengine-macos
          path: qtwebengine.tar
